# Generated by Django 4.0.dev20210403125743 on 2021-04-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_mananger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_mananger.days')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_mananger.user')),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='worker',
            field=models.ManyToManyField(through='shift_mananger.Workers', to='shift_mananger.User'),
        ),
    ]
